# Generated by Django 5.2.5 on 2025-08-09 01:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockingJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ligand_smiles', models.TextField(help_text='SMILES string of the ligand')),
                ('receptor_pdb_id', models.CharField(help_text='PDB ID of the receptor', max_length=10)),
                ('center_x', models.FloatField(help_text='X coordinate of binding site center')),
                ('center_y', models.FloatField(help_text='Y coordinate of binding site center')),
                ('center_z', models.FloatField(help_text='Z coordinate of binding site center')),
                ('size_x', models.FloatField(help_text='Search space size in X dimension')),
                ('size_y', models.FloatField(help_text='Search space size in Y dimension')),
                ('size_z', models.FloatField(help_text='Search space size in Z dimension')),
                ('exhaustiveness', models.IntegerField(default=8, help_text='Thoroughness of search')),
                ('num_modes', models.IntegerField(default=9, help_text='Number of binding modes to generate')),
                ('results_json', models.JSONField(blank=True, help_text='Docking results in JSON format', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
