# Generated by Django 5.2.5 on 2025-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobtemplate_dockingjob_advanced_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockingjob',
            name='engine',
            field=models.CharField(blank=True, help_text='Docking engine used (vina, mock, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dockingjob',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Whether mock docking was used'),
        ),
    ]
