# Generated by Django 5.2.5 on 2025-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_engine_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockingjob',
            name='seed',
            field=models.IntegerField(blank=True, help_text='Random seed for reproducible results', null=True),
        ),
    ]
