# Generated by Django 5.2.5 on 2025-08-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_seed_parameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bindingpocket',
            options={'ordering': ['-druggability_score', '-confidence_score']},
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='accessibility',
            field=models.CharField(blank=True, help_text='Accessibility level (buried, surface, partially_buried)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='cavity_type',
            field=models.CharField(blank=True, help_text='Type of cavity (deep, shallow, tunnel, cleft)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='chemical_environment',
            field=models.JSONField(blank=True, help_text='Chemical environment analysis', null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='conservation_score',
            field=models.FloatField(blank=True, help_text='Evolutionary conservation score', null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='detection_software',
            field=models.CharField(blank=True, help_text='Software used for detection', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='druggability_analysis',
            field=models.JSONField(blank=True, help_text='Detailed druggability analysis', null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='pocket_rank',
            field=models.IntegerField(blank=True, help_text='Rank among detected pockets', null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='shape_analysis',
            field=models.JSONField(blank=True, help_text='Shape and geometry analysis', null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='surface_area',
            field=models.FloatField(blank=True, help_text='Pocket surface area in square Angstroms', null=True),
        ),
        migrations.AddField(
            model_name='bindingpocket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bindingpocket',
            name='detection_method',
            field=models.CharField(default='geometric_analysis', help_text='Method used for detection', max_length=50),
        ),
        migrations.AlterField(
            model_name='bindingpocket',
            name='radius',
            field=models.FloatField(blank=True, help_text='Pocket radius in Angstroms', null=True),
        ),
    ]
