# Generated by Django 5.2.5 on 2025-08-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_enhanced_pocket_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockingjob',
            name='estimated_seconds_remaining',
            field=models.FloatField(blank=True, help_text='Estimated seconds remaining', null=True),
        ),
        migrations.AddField(
            model_name='dockingjob',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, help_text='Last progress update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='dockingjob',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Human-readable progress message', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dockingjob',
            name='progress_percent',
            field=models.FloatField(blank=True, help_text='Job progress percent (0-100)', null=True),
        ),
    ]
